### ISSUE TITLE
Script updates for AHK v2?

### ISSUE THREAD

**Issue by jacktose** [scottrippey/ScottoHotKey#2]
Hi Scott,

I've been happily using your AutoInclude script since the [Lifehacker post]—many, many thanks! I was just setting it up on a new machine and AHK says it requires version 1. Are you still using this, and have you looked at updating it for version 2?
For comparison,[ here's a recent post with a different script doing something similar][new script].

–Jack

[Lifehacker post]: https://lifehacker.com/autohotkey-autoinclude-organizes-consolidates-your-ahk-5457619
[new script]: https://www.autohotkey.com/boards/viewtopic.php?f=82&t=116070

**Comment by scottrippey** [comment]
Wow, I totally forgot about that post!  13 years ago :) Wow!
Yes, I still use AHK on my PC, but I have WAY fewer scripts now.  
Unfortunately, I still use V1 too, and haven't upgraded to V2.
